name: Scrape Zabka

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run scraper
        run: npm run scrape

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add products.json
          git commit -m "Auto-update products.json" || echo "No changes"
          git push